---
chat-format: '{WORLD_NAME}:[{TAGS}][{PREFIX}]<{DISPLAY_NAME}> {MESSAGE}'
enable-formatter: true
disablechat: false
default-player-prefix: PFX
default-player-tags: TAGS
CustomChat options: '{Kills} | {Deaths} | [{Money}$]'
CustomJoin: '@Player joined the server ! Iksaku is Awesome'
CustomLeave: '@Player leave the server ! Iksaku is Awesome'
if-player-has-no-faction: NoFaction

...
