name: SignStats
version: 1.0.0
api: 1.11.0
main: Praxthisnovcht\SignStats\SignStats
author: [Praxthisnovcht]
description: Check Stats Sign

permissions:
 signstats.perms.sign:
  description: Create SignStats
commands:
 stats:
  description: "View Stats Users (Kills-Deaths-Ratio)"
  permission: signstats.commands.stats