 # CustomChat by Praxthisnovchtcht Config Message;
############################################################################
############################################################################
# Custom message for Popup
CustomJoin-Message: '@Player joined the server ! Iksaku is Awesome!'
CustomLeave-Message: '@Player leave the server ! Iksaku is Awesome!'
############################################################################
# Duration Popup for CustomJoin {} Tick Per Second
Duration: 3
############################################################################
############################################################################
                                  # AUTO MESSAGE (POPUP/SendMessage)
############################################################################
#Duration Popup for Auto Message {} Tick Per Second
Duration: 3
############################################################################
# Time Intereval Message For AutoMessage (Tick Per Second)
Time_AutoMessage: 20
############################################################################
# Message for Popup and Message for Auto Message
Message1: CustomChat 2.0.0 
Message2: By Praxhisnovcht
Message3: And Co-Developpeur
Message4: Aspraranc and Evolsoft is Awesome
Message4: CustomChat 2.0.0
Message5: CustomChat 2.0.0
############################################################################
# Prefix Tags for Auto Message 
Prefix: CC-Message
############################################################################
# Color For Prefix (AutoMessage)
Color: 
############################################################################
#Color Setting
#BLACK = "§0";
#DARK_BLUE = "§1";
#DARK_GREEN = "§2";
#DARK_AQUA = "§3";
#DARK_RED = "§4";
#DARK_PURPLE = "§5";
#GOLD = "§6";
#GRAY = "§7";
#DARK_GRAY = "§8";
#BLUE = "§9";
#GREEN = "§a";
#AQUA = "§b";
#RED = "§c";
#LIGHT_PURPLE = "§d";
#YELLOW = "§e";
#WHITE = "§f";
############################################################################
