name: CustomChat
version: INDEV
api: 1.12.0
main: Praxthisnovcht\CustomChat\ccMain
author: [Praxthisnovcht]
description: Adds options on the discution salon
commands:
 setprefix:
  description: "sets prefix for player"
  permission: customchat.plugin.setprefix
 defprefix:
  description: "sets default prefix for new players"
  permission: customchat.plugin.defprefix
 delprefix:
  description: "set player's prefix to default"
  permission: customchat.plugin.delprefix
 setnick:
  description: "sets player's nick"
  permission: customchat.plugin.setnick
 delnick:
  description: "returns players's real name"
  permission: customchat.plugin.delnick
 mute:
  description: "mute player from chat"
  permission: customchat.plugin.mute
 unmute:
  description: "unmute player from chat"
  permission: customchat.plugin.unmute
 disablechat:
  description: "disable chat for all players"
  permission: customchat.plugin.offchat
 enablechat:
  description: "enable chat for all player"
  permission: customchat.plugin.onchat
 customchat:
  description: "CustomChat Features"
  permission: customchat.plugin.info
 tags:
  description: "sets tags for Player"
  permission: customchat.plugin.tags
 deftags:
  description: "sets default tags for new players"
  permission: customchat.plugin.defprefix
 deltags:
  description: "set player's tags to default"
  permission: customchat.plugin.tags
 disableworld:
  description: "Disable PerWorldChat for all players"
  permission: customchat.plugin.disableworld
 enableworld:
  description: "Enable PerWorldChat for all players"
  permission: customchat.plugin.enableworld
 alert:
  description: "Simple Alert"
  permission: customchat.plugin.alert
