

---
# Available PureChat with PureKill tags: {Kills}, {Deaths},
groups:
  Guest:
    chat: "&3&l{prefix}&e[Guest]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&e[Guest]&f&r {display_name}"
    worlds: []
  Admin:
    chat: "&3&l{prefix}&c[Admin]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&c[Admin]&f&r {display_name}"
    worlds: []
  Owner:
    chat: "&3&l{prefix}&a[Owner]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&a[Owner]&f&r {display_name}"
    worlds: []
  OP:
    chat: "&3&l{prefix}&9[OP]&f&r {display_name} &7> {msg}"
    nametag: "&3&l{prefix}&9[OP]&f&r {display_name}"
    worlds: []
...